name: Vault secrets
description: Vault
inputs:
  WORKFLOW_TYPE: 
    description: 'Workflow type'
    required: true
  VAULT_SERVER_URL:
    description: 'Vault-URL'
    required: true
  VAULT_NAMESPACE:
    description: 'Vault-namespace'
    required: true
  VAULT_TOKEN:
    description: 'VAULT token'
    required: true

 
runs:
  using: 'composite'
  steps:
    - name: Vault
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        VAULT_ADDR: "http://127.0.0.1:8200"
        VAULT_NAMESPACE: ""
        VAULT_TOKEN: "s.m76oOBDI61an1xNtVMs7KMza"

      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault
        echo 'VAULT_TOKEN=>'
        echo $VAULT_TOKEN
        vault login $VAULT_TOKEN
        if [[ "${{inputs.WORKFLOW_TYPE}}" == "polaris" ]]; then
        echo "POLARIS_ACCESS_TOKEN=$(vault kv get -field=POLARIS_ACCESS_TOKEN secret/pilot-project)" >> $GITHUB_ENV
        echo "POLARIS_SERVER_URL=$(vault kv get -field=POLARIS_SERVER_URL secret/pilot-project)" >> $GITHUB_ENV
        echo "SLACK_CHANNEL_NAME=$(vault kv get -field=SLACK_CHANNEL_NAME secret/pilot-project)" >> $GITHUB_ENV
        echo "SLACK_API_TOKEN=$(vault kv get -field=SLACK_API_TOKEN secret/pilot-project)" >> $GITHUB_ENV
        fi





