name: Container
on: [pull_request]
jobs:
  php-docker:
    runs-on: ubuntu-latest
    container:
      image: php:8.0.6-cli-buster
    steps:
      - name: log php version
        run: php -v
      - name: Steps with php-docker
        uses: docker://php:8.0.6-zts-buster
        with:
          entrypoint: '/bin/echo'
          args: 'Hello Laxmi'
      - name: logs version with php-docker
        uses: docker://php:8.0.6-zts-buster
        with:
          entrypoint: '/usr/local/bin/php'
          args: -v
      - name: Push a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: "Hello Laxmi, this is slack message!!!"