name: fetch vault
on: [push]
jobs:
  fetch-vault-secrets:
    name: 'Polaris secrets stored in vault' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - uses: hashicorp/vault-action@v2.0.1
        with: 
          url: "http://127.0.0.1:8200"
          tlsSkipVerify: true
          token: "s.ebUXzEd8Q2JrY8HzF6IyhH6B"
          secrets: |
          kv/data/ci/dockerUsername DOCKERHUB_USERNAME
          kv/data/ci/dockerPassword DOCKERHUB_PASSWORD


