name: fetch vault
on: [push]
jobs:
  fetch-vault-secrets:
    name: 'Polaris secrets stored in vault' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
          repository: laxmi-priyam/github-actions-test
          ssh-strict: false
      - uses: ./.github/actions/vault
        with: 
          WORKFLOW_TYPE: "polaris"
          tlsSkipVerify: true
          VAULT_SERVER_URL: "http://127.0.0.1:8200"
          VAULT_NAMESPACE: ""
          VAULT_TOKEN: "s.ebUXzEd8Q2JrY8HzF6IyhH6B"
