name: second worflow

on: [push]

jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    steps:
      -name: javascript-action
      uses: actions/hello-world-javscript-action@v1
      id: greet
      with:
        who-to-greet: Laxmi
      -name: display output
      run: echo "{{steps.greet.outputs.time}}"