name : Sample commands

on : [push]

jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v1
        run: |
          pwd
          ls -a
      - name: javascript-action
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: Laxmi
      - name: display output
        run: echo "${{steps.greet.outputs.time}}"