name : Shell-commands

on : [push]

jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name : echo a string
        run : echo "Hello Laxmi"
      - name : multiline script
        run : |
         npm -v
         node -v
  runs-windows-commands:
    runs-on: windows-latest
    steps:
      - name : python command
        run : |
          import platform
          print(platform.processor())
        shell: python  
